= Chronicle Salt - Java binding to wrap libsodium which implements the NaCl crypto library
Peter Lawrey

This library natively support Chronicle Bytes and can sign and verify data entirely off heap. This saves copying data to/from byte[] (not creating them)

=== Based on
This library is a port of the https://github.com/abstractj/kalium[Abstractj Kalium] library to use Chronicle Bytes off heap instead of byte[] on heap.

=== Requirements

* JDK 8 or http://www.oracle.com/technetwork/java/javase/downloads/index.html[higher]
* http://maven.apache.org/guides/getting-started/[Apache Maven]

=== Installation

==== libsodium

Chronicle Salt is implemented using https://github.com/jnr/jnr-ffi[jnr-ffi]
to bind the shared libraries from https://github.com/jedisct1/libsodium[libsodium].
For a more detailed explanation, please refer to
https://github.com/cryptosphere/rbnacl/blob/master/README.md[RbNaCl's documentation]

==== Linux

Linux users can download the source tar for Linux

- Download `libsodium` from https://download.libsodium.org/libsodium/releases/
- Choose the version of `libsodium` you wish to use
    - The archives follow the following pattern: libsodium-{version}.tar.gz
- `tar xzvf libsodium-{version}.tar.gz`
- `cd libsodium-{version}`
- `./configure`
- `make`
- `sudo make install`

==== OSX

OS X users can get libsodium via http://mxcl.github.com/homebrew/[homebrew] with:

    brew install libsodium

==== Windows

Windows users will need to provide the pre-build binaries from `libsodium`.

- Download `libsodium` from https://download.libsodium.org/libsodium/releases/
- Choose the version of `libsodium` you wish to use
    - The archives follow the following pattern: libsodium-{version}-msvc.zip
- From the archive find the artifacts compiled for your architecture and then the MSVC tool set of your choice
    - For example: `v141 // these were compiled against the MSVC v141 (i.e. Visual Studio 2017)`
- Extract from the archive the `dll` library files into **one** of the following locations:
    - into the `lib` at the root of the working directory directory of your project.
    - into a location that is included in your `PATH` environment variable.

For example, on my Windows 10 machine with a x64 architecture:
```
{archive root}
└───x64
    ...
    └───Release
        ...
        └───v141
            ...
            └───dynamic <- copy the library files from this locaiton.
```

== Using Chronicle Salt

=== Generating Random Bytes

TBC

=== Generating a public and secret key from a private key

To use Ed25519 you need to create a public key from a private one.

[source, Java]
----
    Bytes seed = generateRandomBytes(32);
    Bytes secretKey = bytesWithZeros(32 * 2);
    Bytes publicKey = bytesWithZeros(32);
    Ed25519.privateToPublicAndSecret(publicKey, secretKey, seed);
----

